spring.application.name=ms-boletos

# URL de ms-asientos
ms-asientos.base-url=http://localhost:8082

# Resource Server — validación de JWT emitido por Google Auth Platform
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
